<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-JSLH211" failures="2" tests="22" name="testrunner.Runnerclass" time="402.443" errors="0" timestamp="2023-12-12T18:29:03 CST" skipped="0">
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="16.134"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="10.179"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="9.776"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="9.300"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="7.576"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="15.876"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="8.625"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="7.350"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="21.256"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="7.581"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="14.349"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="7.427"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="6.628"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="12.277">
    <failure message="expected [12-12-2023] but found [12-13-2023]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [12-12-2023] but found [12-13-2023]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepdefinitions.Sign_SD.the_user_is_navigated_to_the_view_guests_page_successfully(Sign_SD.java:210)
at ✽.The user is navigated to the View guests page successfully(file:///C:/Users/amitf/eclipse-workspace/Restassured/DtcWebsite/src/test/resources/Features/Signup.feature:53)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="9.701"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="20.237"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="53.905"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="6.163"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="7.469"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="104.963"/>
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="9.200">
    <failure message="The following asserts failed:
	expected [Please make sure all the required fields are completed] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please make sure all the required fields are completed] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at stepdefinitions.Sign_SD.the_error_message_to_fill_fields_is_displayed(Sign_SD.java:298)
at ✽.The error message to fill fields is displayed(file:///C:/Users/amitf/eclipse-workspace/Restassured/DtcWebsite/src/test/resources/Features/Signup.feature:85)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runnerclass" name="runScenario" time="36.471"/>
  <system-out/>
</testsuite> <!-- testrunner.Runnerclass -->
